# Generated by Django 3.2.9 on 2021-12-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepo_app', '0004_auto_20211213_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
